# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 712ed706f5f7f1ff5e31d2d9f93fdd2c8aed09d4337a14637798525ef103938a0cf133e28aaca2bed9e01004508cb91fdbeb51508668643cf3a2a4bdd1748c5a

test:
  secret_key_base: 2c935bfc5af9e0eecb5ae27c8d9c89a12a30a79374931b07e9bf33de03b5ba0ac71b7a610c635b53b1bd48a6cd102af1a6815307f7e82c11dad40a9238adf868

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
